
name: "Multi event pipeline / workflows"

# Controls when the action will run. Triggers the workflow on push some to master or production branch.

on:
    push:
        branches:
            - master
            - test

jobs:
    hello_word: 
        runs-on: ubuntu-latest
        steps:
            - name: "Print hello world"
              run: echo "Hello world"